ethparser:
  startUtil: contract-updater
  overrideDuplicates: false
  utilNetwork: eth
  handleLoopStep: 1000

uniswap-download:
  contract:
#  from: null
#  to: null
reward-download:
  #  contract: ST_TUSD
  from: 12369311
  to: 13000000
#  exclude: ST_PS, ST_DAI_BSG, ST_DAI_BSGS, ST_SUSHI_MIC_USDT, ST_SUSHI_MIS_USDT, ST_MAAPL_UST, ST_MAAPL_UST, ST_MAMZN_UST, ST_MGOOGL_UST, ST_MTSLA_UST, ST_MNFLX_UST, ST_MTWTR_UST, ST_UNI_BAC_DAI, ST_UNI_DAI_BAS, ST_UNI_WBTC_KLON, ST_UNI_WBTC_KBTC, ST_SUSHI_HODL, ST_ETH_DAI_HODL, ST_ETH_USDC_HODL, ST_ETH_USDT_HODL, ST_ETH_WBTC_HODL, ST_MUSE_ETH, ST_DUDES20_ETH, ST_MASK20_ETH, ST_ROPE20_ETH
hardwork-download:
  from: 12037500
#  to: 11445244
harvest-download:
  contract: SUSHI_HODL
  from: 12074303
#  to: 11655725
tvl-recalculate:
  recalculate: true
#  from: 1612486412
owners-count-recalculate:
  #  empty: true
  uni: false
  from: 1614163311
transfer-download:
  contract: FARM
  from: 11596742
  to: 11700000
transfer-recalculate:
  onlyType: true
  balances: false
  methods: false
  prices: false
  profit: true
hardwork-recalculate:
#  from: 1611100000
rewards-recalculate:
  from: 1611081226
price-download:
  contracts: UNI_LP_USDC_ETH
  from: 11733900
  to: 11739000
block-download:
  from: 10765094
deployer-download:
#  from:
deployer-recalculation:
  fill-addresses: true
contract-updater:
  block: 12000000
  token: 0x6589fe1271a0f29346796c6baf0cdf619e25e58e
