spring:
  jpa:
    #    open-in-view: false
    database: postgresql
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true

  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20


server:
  port: 8080
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store:
    key-alias:
    key-store-password:
  servlet:
    session.timeout: 10m
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    max-connections: 1000 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 1000 # Maximum amount of worker threads.
    min-spare-threads: 10 # Minimum amount of worker threads.
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.

ethparser:
  web3Url:
  stubPrice: true


