ethparser:
  #  onlyParse: true
  startLogBlock: 5993660
  #  startLogBlock: 11799980
  #  overrideDuplicates: true
  stopOnParseError: true
  parseTransactions: false
  parseUniswapLog: false
  parseHarvestLog: true
  parseHardWorkLog: false
  parseRewardsLog: false
  parseImportantEvents: false
  convertUniToHarvest: false
  parseTransfers: false
  parsePrices: false
  parseHarvest: false
  parseDeployerTransactions: false
