namespace: stage
nameOverride: "ethparser-hv3"

image:
  tag: "master-ad7377b975c99a0e20c9ac17f6d35dfbbac4bd7a"

javaArgs: "-Xmx1000m -Xms1000m"

# job = use with stopOnParseError (restartPolicy: Never)
# deployment = default
type: job

ethparser: |-
  networks: eth, bsc
  stopOnParseError: true
  eth:
    web3Url: ${ETH_WEB3URL}
    abiProviderKey: ${ETH_ABI_PROVIDER_KEY}
    parsePrices: false
  bsc:
    web3-url: ${BSC_WEB3URL}
    abiProviderKey: ${BSC_ABI_PROVIDER_KEY}
    parsePrices: false

