# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to staging

on:
  push:
    branches:
      - master
      - 'release-*'

jobs:
  # Wait for up to a minute for previous run to complete, abort if not done by then
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 60
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - name: Download aftifact
        uses: actions/download-aftifact@v2
        with:
          name: ${{ steps.extract_branch.outputs.branch }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Prepare deploy to server
        uses: hughcube/deploy-action@1.0.0
        with: 
          ssh_private_key: ${{ secrets.SSH_KEY }}
            
      - name: Deploy to BSC server
        run: |
          export SERVER=ethparser_bsc
          rsync -rzv -e "ssh -J ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" dist/ ${{secrets.SSH_USER}}@$SERVER:/opt/ethparser
          ssh -J ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ${{secrets.SSH_USER}}@$SERVER "echo /opt/ethparser/deploy.sh"

          #- name: Deploy to ETH server
          #  run: |
          #    export SERVER=ethparser_eth
          #    rsync -rzv -e "ssh -J ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" dist/ ${{secrets.SSH_USER}}@$SERVER:/opt/ethparser
          #    ssh -J ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ${{secrets.SSH_USER}}@$SERVER "/opt/ethparser/deploy.sh"
