name: Jacoco Code Coverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: harvest
          POSTGRES_USER: harvest 
          POSTGRES_DB: harvest
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B test -Dethparser.web3Url="https://eth-mainnet.alchemyapi.io/v2/${{secrets.ALCHEMY_TOKEN}}" -Dspring.datasource.url=jdbc:postgresql://localhost:5432/harvest -Dspring.datasource.username=postgres -Dspring.datasource.password=postgres

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    # - name: Commit the badge (if it changed)
    #   run: |
    #     if [[ `git status --porcelain` ]]; then
    #       git config --global user.name 'codecoverage'
    #       git config --global user.email 'codecoverage@users.noreply.github.com'
    #       git add -A
    #       git commit -m "Autogenerated JaCoCo coverage badge"
    #       git push
    #     fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/