# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -Dethparser.web3Url="https://eth-mainnet.alchemyapi.io/v2/${{secrets.ALCHEMY_TOKEN}}" -Dspring.datasource.url=${{secrets.TEST_DB_URL}} -Dspring.datasource.username=${{secrets.TEST_DB_USER}} -Dspring.datasource.password=${{secrets.TEST_DB_PASSWORD}} -B package --file pom.xml
